//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.WSsitedTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.susalud.gob.pe/ServiceAcreditacion/", ConfigurationName="WSsitedTest.ServiceAcreditacion")]
    public interface ServiceAcreditacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.susalud.gob.pe/ServiceAcreditacion/busquedaDatosAsegurado", ReplyAction="*")]
        CapaPresentacion.WSsitedTest.busquedaDatosAseguradoResponse busquedaDatosAsegurado(CapaPresentacion.WSsitedTest.busquedaDatosAseguradoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.susalud.gob.pe/ServiceAcreditacion/busquedaDatosAsegurado", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaPresentacion.WSsitedTest.busquedaDatosAseguradoResponse> busquedaDatosAseguradoAsync(CapaPresentacion.WSsitedTest.busquedaDatosAseguradoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class busquedaDatosAseguradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="busquedaDatosAsegurado", Namespace="http://www.susalud.gob.pe/ServiceAcreditacion/", Order=0)]
        public CapaPresentacion.WSsitedTest.busquedaDatosAseguradoRequestBody Body;
        
        public busquedaDatosAseguradoRequest() {
        }
        
        public busquedaDatosAseguradoRequest(CapaPresentacion.WSsitedTest.busquedaDatosAseguradoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class busquedaDatosAseguradoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string txNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string coRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string txPeticion;
        
        public busquedaDatosAseguradoRequestBody() {
        }
        
        public busquedaDatosAseguradoRequestBody(string txNombre, string coRemitente, string txPeticion) {
            this.txNombre = txNombre;
            this.coRemitente = coRemitente;
            this.txPeticion = txPeticion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class busquedaDatosAseguradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="busquedaDatosAseguradoResponse", Namespace="http://www.susalud.gob.pe/ServiceAcreditacion/", Order=0)]
        public CapaPresentacion.WSsitedTest.busquedaDatosAseguradoResponseBody Body;
        
        public busquedaDatosAseguradoResponse() {
        }
        
        public busquedaDatosAseguradoResponse(CapaPresentacion.WSsitedTest.busquedaDatosAseguradoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class busquedaDatosAseguradoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string coError;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string txNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string coRemitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string txRespuesta;
        
        public busquedaDatosAseguradoResponseBody() {
        }
        
        public busquedaDatosAseguradoResponseBody(string coError, string txNombre, string coRemitente, string txRespuesta) {
            this.coError = coError;
            this.txNombre = txNombre;
            this.coRemitente = coRemitente;
            this.txRespuesta = txRespuesta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceAcreditacionChannel : CapaPresentacion.WSsitedTest.ServiceAcreditacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAcreditacionClient : System.ServiceModel.ClientBase<CapaPresentacion.WSsitedTest.ServiceAcreditacion>, CapaPresentacion.WSsitedTest.ServiceAcreditacion {
        
        public ServiceAcreditacionClient() {
        }
        
        public ServiceAcreditacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAcreditacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAcreditacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAcreditacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.WSsitedTest.busquedaDatosAseguradoResponse CapaPresentacion.WSsitedTest.ServiceAcreditacion.busquedaDatosAsegurado(CapaPresentacion.WSsitedTest.busquedaDatosAseguradoRequest request) {
            return base.Channel.busquedaDatosAsegurado(request);
        }
        
        public string busquedaDatosAsegurado(ref string txNombre, ref string coRemitente, string txPeticion, out string txRespuesta) {
            CapaPresentacion.WSsitedTest.busquedaDatosAseguradoRequest inValue = new CapaPresentacion.WSsitedTest.busquedaDatosAseguradoRequest();
            inValue.Body = new CapaPresentacion.WSsitedTest.busquedaDatosAseguradoRequestBody();
            inValue.Body.txNombre = txNombre;
            inValue.Body.coRemitente = coRemitente;
            inValue.Body.txPeticion = txPeticion;
            CapaPresentacion.WSsitedTest.busquedaDatosAseguradoResponse retVal = ((CapaPresentacion.WSsitedTest.ServiceAcreditacion)(this)).busquedaDatosAsegurado(inValue);
            txNombre = retVal.Body.txNombre;
            coRemitente = retVal.Body.coRemitente;
            txRespuesta = retVal.Body.txRespuesta;
            return retVal.Body.coError;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.WSsitedTest.busquedaDatosAseguradoResponse> CapaPresentacion.WSsitedTest.ServiceAcreditacion.busquedaDatosAseguradoAsync(CapaPresentacion.WSsitedTest.busquedaDatosAseguradoRequest request) {
            return base.Channel.busquedaDatosAseguradoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.WSsitedTest.busquedaDatosAseguradoResponse> busquedaDatosAseguradoAsync(string txNombre, string coRemitente, string txPeticion) {
            CapaPresentacion.WSsitedTest.busquedaDatosAseguradoRequest inValue = new CapaPresentacion.WSsitedTest.busquedaDatosAseguradoRequest();
            inValue.Body = new CapaPresentacion.WSsitedTest.busquedaDatosAseguradoRequestBody();
            inValue.Body.txNombre = txNombre;
            inValue.Body.coRemitente = coRemitente;
            inValue.Body.txPeticion = txPeticion;
            return ((CapaPresentacion.WSsitedTest.ServiceAcreditacion)(this)).busquedaDatosAseguradoAsync(inValue);
        }
    }
}
